apiVersion: v1
kind: Pod
metadata:
  name: argo-test-pod
spec:
    containers:
      - name: web
        image: quay.io/centos7/httpd-24-centos7
        resources: 
           requests:
              memory: "500Mi"
           limits:
              memory: "1024Mi"
